/* R9 clean-room gameplay controller: CONSULT -> PREP -> WOK -> SERVE -> RESULT. */
(() => {
  'use strict';
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const rules=window.CKClinicRules;
  if(!rules) throw new Error('CKClinicRules is required');
  const stages=['consult','prep','wok','serve'];
  const symptoms=[['craving','Craving','菸癮'],['irritability','Irritability','煩躁'],['anxiety','Anxiety','焦慮'],['concentration','Concentration','集中困難'],['restlessness','Restlessness','坐立難安'],['appetite','Appetite','食慾困難'],['sleep','Sleep','睡眠困擾']];
  const foodOrder=['tofu','pork','douban','garlic','scallion','chili','pepper'];
  const food={
    tofu:{name:'豆腐',src:'assets/cooking/tofu_cubes.png',target:'固定基底'},
    pork:{name:'絞肉',src:'assets/cooking/pork_raw_mound.png',target:'固定基底'},
    douban:{name:'豆瓣醬',src:'assets/ingredients/mapo_tofu/douban.png',target:'Craving'},
    garlic:{name:'蒜',src:'assets/cooking/garlic_mince.png',target:'Irritability'},
    scallion:{name:'青蔥',src:'assets/cooking/scallion_rings.png',target:'Concentration'},
    chili:{name:'辣椒',src:'assets/ingredients/mapo_tofu/chili.png',target:'Restlessness'},
    pepper:{name:'花椒',src:'assets/ingredients/mapo_tofu/pepper.png',target:'Anxiety'}
  };
  const dom={ticket:q('#ticketNumber'),patientName:q('#patientName'),patientPortrait:q('#patientPortrait'),patientComplaint:q('#patientComplaint'),ftndScore:q('#ftndScore'),ftndSeverity:q('#ftndSeverity'),ftndItems:q('#ftndItems'),symptomList:q('#symptomList'),prescriptionGrid:q('#prescriptionGrid'),workflow:q('#workflow'),doctorMarker:q('#doctorMarker'),stagePanel:q('#stagePanel'),statusBar:q('#statusBar')};
  const state={ticket:1,patientIndex:0,stage:'consult',portions:{},stirs:0,simmerReady:false,simmerTimer:null,rice:null,miso:null,result:null,clinical:null,review:null,won:null};
  const patient=()=>rules.patients[state.patientIndex%rules.patients.length];
  const prescription=()=>rules.buildClinicalPrescription(patient());
  const ticketText=()=>String(state.ticket).padStart(3,'0');
  const portionText=v=>Number(v)===0?'0':Number(v)===0.5?'1/2':'1';
  const resetPortions=()=>{state.portions={tofu:1,pork:1,douban:0,garlic:0,scallion:0,chili:0,pepper:0};};
  const clearTimer=()=>{if(state.simmerTimer)clearTimeout(state.simmerTimer);state.simmerTimer=null;};

  function button(id,label,handler,disabled=false,klass='primary-action'){
    const b=document.createElement('button');b.id=id;b.type='button';b.className=klass;b.textContent=label;b.disabled=disabled;b.addEventListener('click',handler);return b;
  }
  function shell(kicker,title,desc){const n=document.createElement('div');n.className='stage-shell';const h=document.createElement('header');h.className='stage-head';h.innerHTML='<small>'+kicker+'</small><h2>'+title+'</h2>'+(desc?'<p>'+desc+'</p>':'');n.append(h);return n;}
  function setStage(s){clearTimer();state.stage=s;renderWorkflow();renderStage();}
  function renderWorkflow(){const railStage=state.stage==='result'?'consult':state.stage;const step=Math.max(0,stages.indexOf(railStage));dom.workflow.dataset.stage=railStage;qa('.station',dom.workflow).forEach((n,i)=>{n.classList.toggle('is-active',i===step);n.classList.toggle('is-done',state.stage!=='result'&&i<step);n.setAttribute('aria-current',i===step?'step':'false');});dom.doctorMarker.style.left=(12.5+step*25)+'%';}
  function renderPatient(){
    const p=patient(),rx=prescription();dom.ticket.textContent=ticketText();dom.patientName.textContent=p.name;dom.patientPortrait.src='assets/service/'+p.id+'.webp';dom.patientPortrait.alt=p.name+' 病人插畫';dom.patientComplaint.textContent='「'+(p.complaint||p.wish||'')+'」';dom.ftndScore.textContent=p.ftnd?.total??'-';dom.ftndSeverity.textContent=p.ftnd?.severity??'';dom.ftndItems.replaceChildren();
    for(let i=1;i<=6;i++){const s=document.createElement('span');s.textContent='Q'+i+' '+(p.ftnd?.['q'+i]??'-');dom.ftndItems.append(s);}dom.symptomList.replaceChildren();
    symptoms.forEach(([key,en,zh])=>{const v=Number(p.clinicalStatus?.[key]??0),row=document.createElement('div');row.className='symptom-row';row.innerHTML='<div class="symptom-label"><span>'+en+'</span><b>'+zh+'</b></div><div class="symptom-bar"><i style="width:'+(v/4*100)+'%"></i></div><strong>'+v+'/4</strong>';dom.symptomList.append(row);});
    dom.prescriptionGrid.replaceChildren();
    [['douban',rx.portions.douban,'Craving'],['garlic',rx.portions.garlic,'Irritability'],['pepper',rx.portions.pepper,'Anxiety'],['scallion',rx.portions.scallion,'Concentration'],['chili',rx.portions.chili,'Restlessness']].forEach(([id,v,t])=>{const c=document.createElement('div');c.className='rx-card';c.innerHTML='<img src="'+food[id].src+'" alt="'+food[id].name+'"><div><small>'+t+'</small><strong>'+food[id].name+' '+portionText(v)+'</strong></div>';dom.prescriptionGrid.append(c);});
    const rice=document.createElement('div');rice.className='rx-card';rice.innerHTML='<img src="'+(rx.rice==='半碗飯'?'assets/service/portion_half.webp':'assets/service/portion_full.webp')+'" alt="'+rx.rice+'"><div><small>Appetite</small><strong>'+rx.rice+'</strong></div>';dom.prescriptionGrid.append(rice);
    const soup=document.createElement('div');soup.className='rx-card';soup.innerHTML='<img src="'+(rx.miso?'assets/service/miso_yes.webp':'assets/service/miso_no.webp')+'" alt="味噌湯"><div><small>Sleep</small><strong>'+(rx.miso?'味噌湯 YES':'味噌湯 NO')+'</strong></div>';dom.prescriptionGrid.append(soup);
  }
  function renderConsult(){const p=patient(),rx=prescription(),n=shell('01 CONSULT · 問診',ticketText()+' 號 '+p.name,'確認主訴與料理處方；接著自動進入備料。'),g=document.createElement('div');g.className='consult-grid';g.innerHTML='<section class="consult-card complaint-card"><small>PATIENT SAYS</small><blockquote>'+(p.complaint||p.wish||'')+'</blockquote></section><section class="consult-card target-card"><small>本輪配餐目標</small><strong>'+rx.rice+' · '+(rx.miso?'要味噌湯':'不要味噌湯')+'</strong><p>豆腐與絞肉固定 1 份；其餘依左側 Clinical Prescription。</p></section>';n.append(g);const a=document.createElement('div');a.className='stage-actions';a.append(button('consultConfirmBtn','確認處方 → 開始備料',()=>{resetPortions();state.stirs=0;state.simmerReady=false;state.rice=null;state.miso=null;state.result=null;state.won=null;setStage('prep');}));n.append(a);return n;}
  function ingredientCard(id){const rx=prescription(),meta=food[id],fixed=id==='tofu'||id==='pork',c=document.createElement('article');c.className='ingredient-card';c.dataset.food=id;c.innerHTML='<img src="'+meta.src+'" alt="'+meta.name+'"><div class="ingredient-copy"><strong>'+meta.name+'</strong><small>'+meta.target+(fixed?'':' · 處方 '+portionText(rx.portions[id]))+'</small></div>';const ctr=document.createElement('div');ctr.className='portion-choices';if(fixed){const s=document.createElement('span');s.className='fixed-tag';s.textContent='固定 1';ctr.append(s);}else{[0,0.5,1].forEach(v=>{const b=button('',v===0.5?'半':String(v),()=>{state.portions[id]=v;renderStage();},false,'portion-choice');b.removeAttribute('id');b.dataset.portionChoice='';b.dataset.food=id;b.dataset.value=String(v);b.setAttribute('aria-pressed',String(state.portions[id]===v));ctr.append(b);});}c.append(ctr);return c;}
  function renderPrep(){const n=shell('02 PREP · 備料','設定食材份量','依左側處方設定 5 個可調整食材，完成後自動下鍋。'),layout=document.createElement('div');layout.className='prep-layout';const grid=document.createElement('div');grid.className='ingredient-grid';foodOrder.forEach(id=>grid.append(ingredientCard(id)));const preview=document.createElement('div');preview.className='prep-preview';preview.innerHTML='<img src="assets/cooking/cutting_board_full.png" alt="備料砧板"><div><strong>備料完成後自動下鍋</strong><span>不需要再按下鍋，也不需要切換工作區。</span></div>';layout.append(grid,preview);n.append(layout);const a=document.createElement('div');a.className='stage-actions';a.append(button('prepDoneBtn','備料完成 → 前往炒鍋',()=>{state.stirs=0;state.simmerReady=false;setStage('wok');}));n.append(a);return n;}
  function wokItem(id,slot){const img=document.createElement('img');img.className='wok-item';img.dataset.food=id;img.src=food[id].src;img.alt=food[id].name;img.style.setProperty('--slot',slot);return img;}
  function startSimmer(){clearTimer();state.simmerReady=false;state.simmerTimer=setTimeout(()=>{state.simmerTimer=null;if(state.stage==='wok'){state.simmerReady=true;renderStage();}},1200);}
  function renderWok(){const n=shell('03 WOK · 炒鍋','翻炒 3 次 → 自動收汁','食材已自動下鍋；翻炒三次後系統自動完成標準收汁。'),layout=document.createElement('div');layout.className='wok-layout';const visual=document.createElement('div');visual.className='wok-visual-r9';visual.innerHTML='<img class="wok-pan-r9" src="assets/cooking/wok_empty.png" alt="炒鍋"><div class="wok-food-layer-r9"></div><img class="spatula-r9" src="assets/cooking/metal_spatula.png" alt="鍋鏟">';const layer=q('.wok-food-layer-r9',visual);let slot=0;foodOrder.forEach(id=>{if(Number(state.portions[id]||0)>0)layer.append(wokItem(id,slot++));});if(state.stirs>0)visual.classList.add('has-stirred');if(state.simmerReady)visual.classList.add('is-ready');const controls=document.createElement('div');controls.className='wok-controls-r9';const prog=document.createElement('div');prog.className='stir-progress';prog.innerHTML='<span>翻炒進度</span><strong id="stirProgress">'+state.stirs+'/3</strong>';const stir=button('stirBtn',state.stirs<3?'翻炒 '+state.stirs+'/3':'翻炒完成',()=>{if(state.stirs>=3)return;state.stirs++;if(state.stirs===3)startSimmer();renderStage();},state.stirs>=3);const simmer=document.createElement('div');simmer.id='simmerState';simmer.className='simmer-state '+(state.stirs>=3?'is-active ':'')+(state.simmerReady?'is-ready':'');simmer.innerHTML=state.simmerReady?'<strong>收汁完成</strong><span>標準 4 等效秒已完成</span>':state.stirs>=3?'<strong>自動收汁中</strong><span>請稍候約 1.2 秒</span><i></i>':'<strong>等待翻炒</strong><span>第三次翻炒後自動收汁</span>';const done=button('wokDoneBtn','完成烹調 → 前往配餐',()=>setStage('serve'),!state.simmerReady);controls.append(prog,stir,simmer,done);layout.append(visual,controls);n.append(layout);return n;}
  function choice(id,text,src,active,handler){const b=button(id,'',handler,false,'serve-choice');b.setAttribute('aria-pressed',String(active));b.innerHTML='<img src="'+src+'" alt=""><span>'+text+'</span>';return b;}
  function renderServe(){const rx=prescription(),n=shell('04 SERVE · 配餐','選飯量與味噌湯','兩個選項都要明確選擇；完成後自動送餐並結算。');const target=document.createElement('div');target.className='serve-target';target.innerHTML='<strong>本號目標</strong><span>'+rx.rice+'</span><span>'+(rx.miso?'要味噌湯':'不要味噌湯')+'</span>';n.append(target);const layout=document.createElement('div');layout.className='serve-layout';const tray=document.createElement('div');tray.className='tray-visual';tray.innerHTML='<img src="assets/cooking/tray_served.png" alt="麻婆豆腐餐盤"><small>'+(state.rice||'尚未選飯')+' · '+(state.miso===null?'尚未選湯':state.miso?'味噌湯 YES':'味噌湯 NO')+'</small>';const groups=document.createElement('div');groups.className='serve-choices';const rice=document.createElement('section');rice.innerHTML='<h3>白飯</h3>';const rr=document.createElement('div');rr.className='choice-row';rr.append(choice('riceHalfBtn','半碗飯','assets/service/portion_half.webp',state.rice==='半碗飯',()=>{state.rice='半碗飯';renderStage();}),choice('riceFullBtn','一碗飯','assets/service/portion_full.webp',state.rice==='正常飯',()=>{state.rice='正常飯';renderStage();}));rice.append(rr);const soup=document.createElement('section');soup.innerHTML='<h3>味噌湯</h3>';const sr=document.createElement('div');sr.className='choice-row';sr.append(choice('misoNoBtn','不要','assets/service/miso_no.webp',state.miso===false,()=>{state.miso=false;renderStage();}),choice('misoYesBtn','要','assets/service/miso_yes.webp',state.miso===true,()=>{state.miso=true;renderStage();}));soup.append(sr);groups.append(rice,soup);layout.append(tray,groups);n.append(layout);const ready=state.rice!==null&&state.miso!==null,a=document.createElement('div');a.className='stage-actions';a.append(button('serveDoneBtn',ready?'完成配餐 → 自動送餐':'請先選擇飯量與湯品',finishOrder,!ready));n.append(a);return n;}
  function finishOrder(){if(state.rice===null||state.miso===null)return;const p=patient(),rx=prescription(),order={spicy:p.spicy,scallion:!!p.scallion,rice:rx.rice,miso:rx.miso},dish={contents:{...state.portions},stirs:3,eqSimmerTime:4,highHeatSeconds:4,lowHeatSeconds:0,isSimmered:true,isBurnt:false,rice:state.rice,miso:state.miso};state.result=rules.evaluateR8(order,dish,p);state.clinical=rules.calculateClinicalMetrics(p.clinicalStatus,state.result.quality,state.result.checks,order,dish);state.won=!state.result.hardFail&&state.clinical.success;state.review=rules.generatePatientReview(p,state.result.quality,state.result.checks,dish,state.won);state.stage='result';renderWorkflow();renderStage();}
  function renderResult(){const n=shell('RESULT · 結算',state.won?'料理完成':'處方不符','結果由同一套 R8 評分規則產生。'),hero=document.createElement('div');hero.className='result-hero '+(state.won?'is-win':'is-fail');hero.innerHTML='<img src="'+(state.won?'assets/finale/success_clinic_meal.webp':'assets/finale/failure_table_flip.webp')+'" alt="結算畫面"><div><span class="gate-badge '+(state.result.gateB_pass?'pass':'fail')+'">Gate B '+(state.result.gateB_pass?'PASS':'FAIL')+'</span><strong id="resultQuality">'+state.result.quality+'%</strong><small>料理契合度 · Prescription fidelity <b id="resultFidelity">'+state.result.prescriptionFidelity+'%</b></small><blockquote id="patientReviewQuote">'+state.review.quote+'</blockquote></div>';n.append(hero);const wrap=document.createElement('div');wrap.className='result-table-wrap';const table=document.createElement('table');table.innerHTML='<thead><tr><th>項目</th><th>目標</th><th>實際</th><th>結果</th></tr></thead><tbody></tbody>';const tb=q('tbody',table);state.result.checks.forEach(c=>{const tr=document.createElement('tr');if(!c.ok)tr.className='is-miss';tr.innerHTML='<td>'+c.label+'</td><td>'+c.expected+'</td><td>'+c.actual+'</td><td>'+(c.ok?'✓':'−'+c.penalty)+'</td>';tb.append(tr);});wrap.append(table);n.append(wrap);const a=document.createElement('div');a.className='stage-actions';a.append(button('nextPatientBtn','叫下一號',()=>{state.ticket++;state.patientIndex=(state.patientIndex+1)%rules.patients.length;resetForPatient();renderAll();}));n.append(a);return n;}
  function renderStage(){dom.stagePanel.replaceChildren();const node=state.stage==='consult'?renderConsult():state.stage==='prep'?renderPrep():state.stage==='wok'?renderWok():state.stage==='serve'?renderServe():renderResult();dom.stagePanel.append(node);dom.statusBar.textContent=state.stage==='result'?ticketText()+' 號完成 · '+(state.won?'成功':'需檢討'):ticketText()+' 號 · '+state.stage.toUpperCase()+' · 醫師自動移動，不需方向鍵';}
  function resetForPatient(){clearTimer();state.stage='consult';resetPortions();state.stirs=0;state.simmerReady=false;state.rice=null;state.miso=null;state.result=null;state.clinical=null;state.review=null;state.won=null;}
  function snapshot(){return {version:'R9_CLEAN_FLOW',ticket:state.ticket,patientIndex:state.patientIndex,stage:state.stage,patient:{...patient()},prescription:JSON.parse(JSON.stringify(prescription())),portions:{...state.portions},stirs:state.stirs,simmerReady:state.simmerReady,rice:state.rice,miso:state.miso,result:state.result?JSON.parse(JSON.stringify(state.result)):null,won:state.won};}
  function renderAll(){renderPatient();renderWorkflow();renderStage();}
  resetForPatient();renderAll();window.CKR9={snapshot,render:renderAll,resetCurrent:()=>{resetForPatient();renderAll();}};
})();
